markdown:         rdiscount
pygments:         true
paginate:         4

title:            陈琦的网络日志
url:              http://acking.github.io/writing/
feed:             /atom.xml
author:
    name:         acking
    email:        hbchenqi@gmail.com
    description:  "acking description"

about:            "acking about."
follow:
    email:        hbchenqi@gmail.com
    github:       https://github.com/acking
    twitter:      
    google:       
    facebook:     
description:      

indexContent:     true
imageLink:        


style:            /css/style.css
blogName:         陈琦的网络日志 
blogDesc:         "记录&&分享"
favicon:          /favicon.ico
theme:            default

disqus:           piznblog

copyright:        Copyright © 2014 All rights reserved.
test:             ok
