baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://blog.acking.vip" # the base hostname & protocol for your site
name: "首页"
title: "ChenQi's BLOG"

language: zh-Hans
timezone: Asia/Shanghai

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

markdown: rdiscount
excerpt_separator: "\n\n"
paginate: 10
paginate_path: "page:num"

gems:
  - jemoji
exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
